spring:
  application:
    name: spring-boot-cmr-discovery-application
server:
  port: 9015

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    region : default
    serviceUrl:
      defaultZone: http://localhost:9015/eureka/
    