spring:
  application:
    name: user-service
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9015/eureka}
  instance:
    preferIpAddress: true