spring:
  application:
    name: content-service
server:
  port: 9012
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9015/eureka}
  instance:
    preferIpAddress: true