spring:
  application:
    name: contentrating-service
server:
  port: 9014
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9015/eureka}
  instance:
    preferIpAddress: true